spring.application.name=project-2026

# repository impl switch: inmemory | redis / jdbc
distributecache.repo.redis.type=redis
distributecache.repo.db.type=jdbc

# degrade and fallback
distributecache.degrade.redis-enabled=true
distributecache.degrade.db-fallback-max-concurrent=64
distributecache.db-init.enabled=true

# redis (single or cluster)
spring.data.redis.timeout=3000ms
spring.data.redis.lettuce.pool.max-active=64
spring.data.redis.lettuce.pool.max-idle=16
spring.data.redis.lettuce.pool.min-idle=4
spring.data.redis.lettuce.pool.max-wait=3000ms

# single redis
spring.data.redis.host=47.119.150.113
spring.data.redis.port=6379
#spring.data.redis.password=

 #cluster redis example (enable when using cluster)
# spring.data.redis.cluster.nodes=127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
# spring.data.redis.cluster.max-redirects=3

# mysql
spring.datasource.url=jdbc:mysql://47.119.150.113:3306/project2026?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root@123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
